Repository duo-dinamico/ServiceReports, pull requests merged in 2022-03, with the labels that each got.

#33 Casino get by id
  api/controllers/casinos.controllers.js
  api/errors/index.js
  api/models/casinos.models.js
  api/routes/casinos.router.js
  api/routes/users.router.js
  api/schemas/casinos/request-schema.js
  api/schemas/casinos/response-schema.js
  api/tests/casinos.spec.js
  api/tests/users.spec.js
  api/validation/casinos.validation.js
  api/validation/utils/validation.js
Labels: enhancement

#41 Added casino deletion
  api/controllers/casinos.controllers.js
  api/models/casinos.models.js
  api/models/users.models.js
  api/routes/casinos.router.js
  api/tests/casinos.spec.js
Labels: enhancement

#42 Improved swagger of the casino.
  api/routes/casinos.router.js
Labels: enhancement

#43 Feature/post casino
  api/controllers/casinos.controllers.js
  api/errors/index.js
  api/models/casinos.models.js
  api/routes/casinos.router.js
  api/routes/users.router.js
  api/schemas/casinos/request-schema.js
  api/tests/casinos.spec.js
  api/validation/casinos.validation.js
  api/validation/users.validation.js
  api/validation/utils/validation.js
Labels: enhancement

#45 Fixed some bugs related to error
  api/errors/index.js
  api/routes/casinos.router.js
  api/tests/casinos.spec.js
  api/tests/users.spec.js
  api/validation/casinos.validation.js
  api/validation/users.validation.js
Labels: bug

#47 Test coverage to 100 percent.
  api/controllers/casinos.controllers.js
  api/controllers/departments.controllers.js
  api/controllers/machines.controllers.js
  api/controllers/services.controllers.js
  api/controllers/users.controllers.js
Labels: enhancement

#55 Improvments to README
  README.md
  api/package.json
  package.json
Labels: documentation

#54 Added node engine minimum to both package.json.
  api/package.json
  package.json
Labels: enhancement

#56 Departments endpoint
  api/controllers/departments.controllers.js
  api/models/departments.models.js
  api/routes/casinos.router.js
  api/routes/departments.router.js
  api/schemas/departments/request-schema.js
  api/schemas/departments/response-schema.js
  api/tests/departments.spec.js
  api/validation/departments.validation.js
  api/validation/utils/validation.js
Labels: enhancement

#63 Small tweak to the readme.
  README.md
Labels: enhancement

#66 Feature/machine get
  api/controllers/machines.controllers.js
  api/db/psql/data/test/machines.json
  api/docs/parameters.yaml
  api/models/machines.models.js
  api/routes/machines.router.js
  api/schemas/machines/request-schema.js
  api/schemas/machines/response-schema.js
  api/tests/machines.spec.js
  api/validation/machines.validation.js
  api/validation/utils/validation.js
Labels: enhancement

#68 Improved swagger of users route.
  api/routes/users.router.js
Labels: documentation, enhancement

#69 Some improvments to the client swagger
  api/routes/clients.router.js
Labels: documentation, enhancement

#70 Some improvments to the departement swagger
  api/routes/departments.router.js
Labels: documentation, enhancement

#71 General improvments to swagger
  api/docs/components.yaml
  api/routes/clients.router.js
  api/routes/departments.router.js
  api/routes/machines.router.js
  api/routes/services.router.js
  api/routes/users.router.js
Labels: documentation, enhancement
